language: go

go:
  - 1.17.x

env:
  - GO111MODULE=on

before_script:
  - rm -f go.sum
  - go get -tags "quic kcp" -v github.com/yunyisec/rpcx@HEAD
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - goveralls -service=travis-ci

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
